language: c
compiler: gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libconfig-dev libfcgi-dev libpq-dev
  - curl -L https://github.com/libuv/libuv/archive/v1.x.tar.gz | tar xzf -
  - (cd libuv-1.x && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
  - mkdir build
  - cd build
  - cmake ..
script: make